export const DnDClasses = [
  {"name": "Artificer", "featuredImg": "https://www.tribality.com/wp-content/uploads/2014/12/artificer.jpg"},
  {"name": "Barbarian", "featuredImg": "https://img.wallpapersafari.com/desktop/1536/864/63/75/H83tfQ.jpg"},
  {"name": "Bard", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Druid", "featuredImg": "https://i2.wp.com/static.comicvine.com/uploads/original/11113/111133571/3492036-druid_by_edli-d2zocxe.jpg"},
  {"name": "Monk", "featuredImg": "https://www.gameoutonline.com/wp-content/uploads/2020/08/dnd-monk-fighting-demons-1200x675.jpg"},
  {"name": "Cleric", "featuredImg": "https://www.tribality.com/wp-content/uploads/2016/11/UA-Cleric-domains-image.jpg"},
  {"name": "Fighter", "featuredImg": "https://media.dnd.wizards.com/styles/second_hubpage_banner/public/images/characters/EN_Classes_Fighter_Header.jpg"},
  {"name": "Mystic", "featuredImg": "https://media.dnd.wizards.com/styles/news_banner_header/public/images/news/UA_DNDMystic_0313.jpg"},
  {"name": "Paladin", "featuredImg": "https://geekandsundry.com/wp-content/uploads/2017/04/Paladin-Feature.png"},
  {"name": "Ranger", "featuredImg": "https://wallpaper.dog/large/980912.jpg"},
  {"name": "Rogue", "featuredImg": "https://geekandsundry.com/wp-content/uploads/2017/06/Rogue-Feature.png"},
  {"name": "RuneScribe", "featuredImg": "https://www.dungeonsolvers.com/wp-content/uploads/2015/10/michal-sztuka-sowa.jpg"},
  {"name": "Sorcerer", "featuredImg": "https://imgix.bustle.com/uploads/image/2020/8/24/aab53e7a-91f9-4c8d-905b-5243a8813ee2-traditional-cover-art-by-magali-villeneuve.jpg?w=2000&h=1090&fit=crop&crop=focalpoint&auto=format%2Ccompress&fp-x=0.7912552891396333&fp-y=0.3311965811965812"},
  {"name": "Warlock", "featuredImg": "https://geekandsundry.com/wp-content/uploads/2017/06/Warlock-Feature.png"},
  {"name": "Wizard", "featuredImg": "https://dmdave.com/wp-content/uploads/2019/01/wizard-696702524-1548134280372.jpg"},
];