export const DnDClasses = [
  {"name": "Artificer", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Barbarian", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Bard", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Druid", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Monk", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Cleric", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Fighter", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Mystic", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Paladin", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Ranger", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Rogue", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "RuneScribe", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Sorcerer", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Warlock", "featuredImg": "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/06/Dungeons-and-Dragons-Bard-Cropped.jpg"},
  {"name": "Wizard", "featuredImg": "https://dmdave.com/wp-content/uploads/2019/01/wizard-696702524-1548134280372.jpg"},
];