export const Sources = [
    {
        "name": "Player's Handbook",
        "id": "PHB",
        "source": "PHB",
        "coverUrl": "img/covers/PHB.png",
        "published": "2014-08-19",
        "author": "Wizards RPG Team",
        "spells": "true",
        "type": "book"
      },
      {
        "name": "Monster Manual",
        "id": "MM",
        "source": "MM",
        "coverUrl": "img/covers/MM.png",
        "published": "2014-09-30",
        "author": "Wizards RPG Team",
        "spells": "false",
        "type": "book"
      },
      {
        "name": "Dungeon Master's Guide",
        "id": "DMG",
        "source": "DMG",
        "coverUrl": "img/covers/DMG.png",
        "published": "2014-12-09",
        "author": "Wizards RPG Team",
        "spells": "false",
        "type": "book"        
      },
      {
        "name": "Dungeon Master's Screen",
        "id": "Screen",
        "source": "Screen",
        "coverUrl": "img/covers/Screen.png",
        "published": "2015-01-20",
        "spells": "false",
        "type": "book"
      },
      {
        "name": "Sword Coast Adventurer's Guide",
        "id": "SCAG",
        "source": "SCAG",
        "coverUrl": "img/covers/SCAG.png",
        "published": "2015-11-03",
        "author": "Wizards RPG Team",
        "spells": "false",
        "type": "book"
      },
      {
        "name": "Adventurers League",
        "id": "AL",
        "source": "AL",
        "coverUrl": "img/covers/AL.png",
        "published": "2016-08-26",
        "spells": "false",
        "type": "book"
      },
      {
        "name": "Volo's Guide to Monsters",
        "id": "VGM",
        "source": "VGM",
        "coverUrl": "img/covers/VGM.png",
        "published": "2016-11-15",
        "author": "Wizards RPG Team",
        "spells": "false",
        "type": "book"
      },
      {
        "name": "Xanathar's Guide to Everything",
        "id": "XGE",
        "source": "XGE",
        "coverUrl": "img/covers/XGE.png",
        "published": "2017-11-21",
        "author": "Wizards RPG Team",
        "spells": "true",
        "type": "book"
      },
      {
        "name": "Mordenkainen's Tome of Foes",
        "id": "MTF",
        "source": "MTF",
        "coverUrl": "img/covers/MTF.png",
        "published": "2018-05-29",
        "author": "Wizards RPG Team",
        "spells": "false",
        "type": "book"
      },
      {
        "name": "Guildmasters' Guide to Ravnica",
        "id": "GGR",
        "source": "GGR",
        "coverUrl": "img/covers/GGR.png",
        "published": "2018-11-20",
        "spells": "true",
        "type": "book"
      },
      {
        "name": "Sage Advice Compendium",
        "id": "SAC",
        "source": "SAC",
        "coverUrl": "img/covers/SAC.png",
        "published": "2019-01-31",
        "spells": "false",
        "type": "book"
      },
      {
        "name": "Acquisitions Incorporated",
        "id": "AI",
        "source": "AI",
        "coverUrl": "img/covers/AI.png",
        "published": "2019-06-18",
        "spells": "true",
        "type": "book"
      },
      {
        "name": "Eberron: Rising from the Last War",
        "id": "ERLW",
        "source": "ERLW",
        "coverUrl": "img/covers/ERLW.png",
        "published": "2019-11-19",
        "spells": "false",
        "type": "book"
      },
      {
        "name": "Dungeons & Dragons vs. Rick and Morty: Basic Rules",
        "id": "RMR",
        "source": "RMR",
        "coverUrl": "img/covers/RMR.png",
        "published": "2019-11-19",
        "spells": "false",
        "type": "book"
      },
      {
        "name": "Explorer's Guide to Wildemount",
        "id": "EGW",
        "source": "EGW",
        "coverUrl": "img/covers/EGW.png",
        "published": "2020-03-17",
        "spells": "true",
        "type": "book"
      },
      {
        "name": "Mythic Odysseys of Theros",
        "id": "MOT",
        "source": "MOT",
        "coverUrl": "img/covers/MOT.png",
        "published": "2020-06-02",
        "spells": "false",
        "type": "book"
      },
      {
        "name": "Tasha's Cauldron of Everything",
        "id": "TCE",
        "source": "TCE",
        "coverUrl": "img/covers/TCE.png",
        "published": "2020-11-17",
        "author": "Wizards RPG Team",
        "spells": "true",
        "type": "book"
      },
      {
        "name": "Dungeon Master's Screen: Wilderness Kit",
        "id": "ScreenWildernessKit",
        "source": "ScreenWildernessKit",
        "coverUrl": "img/covers/ScreenWildernessKit.png",
        "published": "2020-11-17",
        "spells": "false",
        "type": "book"
      },
      {
        "name": "Van Richten's Guide to Ravenloft",
        "id": "VRGR",
        "source": "VRGR",
        "coverUrl": "img/covers/VRGR.png",
        "published": "2021-05-18",
        "spells": "false",
        "type": "book"
      },
      {
        "name": "Lost Mine of Phandelver",
        "id": "LMoP",
        "source": "LMoP",
        "coverUrl": "img/covers/LMoP.png",
        "published": "2014-07-15",
        "storyline": "Starter Set",
        "level": { "start": 1, "end": 5 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Hoard of the Dragon Queen",
        "id": "HotDQ",
        "source": "HotDQ",
        "coverUrl": "img/covers/HotDQ.png",
        "published": "2014-08-19",
        "storyline": "Tyranny of Dragons",
        "level": { "start": 1, "end": 7 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Rise of Tiamat",
        "id": "RoT",
        "source": "RoT",
        "coverUrl": "img/covers/RoT.png",
        "published": "2014-11-04",
        "storyline": "Tyranny of Dragons",
        "level": { "start": 8, "end": 15 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Princes of the Apocalypse",
        "id": "PotA",
        "source": "PotA",
        "coverUrl": "img/covers/PotA.png",
        "published": "2015-04-07",
        "storyline": "Elemental Evil",
        "level": { "start": 1, "end": 15 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Out of the Abyss",
        "id": "OotA",
        "source": "OotA",
        "coverUrl": "img/covers/OotA.png",
        "published": "2015-09-15",
        "storyline": "Rage of Demons",
        "level": { "start": 1, "end": 15 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Curse of Strahd",
        "id": "CoS",
        "source": "CoS",
        "coverUrl": "img/covers/CoS.png",
        "published": "2016-03-15",
        "storyline": "Ravenloft",
        "level": { "start": 1, "end": 10 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Storm King's Thunder",
        "id": "SKT",
        "source": "SKT",
        "coverUrl": "img/covers/SKT.png",
        "published": "2016-09-06",
        "storyline": "Storm King's Thunder",
        "level": { "start": 1, "end": 11 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Tales from the Yawning Portal: Against the Giants",
        "id": "TftYP-AtG",
        "source": "TftYP-AtG",
        "coverUrl": "img/covers/TftYP.png",
        "published": "2017-03-24",
        "publishedOrder": 5,
        "storyline": "Tales from the Yawning Portal",
        "level": { "start": 11, "end": 14 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Tales from the Yawning Portal: Dead in Thay",
        "id": "TftYP-DiT",
        "source": "TftYP-DiT",
        "coverUrl": "img/covers/TftYP.png",
        "published": "2017-03-24",
        "publishedOrder": 4,
        "storyline": "Tales from the Yawning Portal",
        "level": { "start": 9, "end": 11 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Tales from the Yawning Portal: The Forge of Fury",
        "id": "TftYP-TFoF",
        "source": "TftYP-TFoF",
        "coverUrl": "img/covers/TftYP.png",
        "published": "2017-03-24",
        "publishedOrder": 1,
        "storyline": "Tales from the Yawning Portal",
        "level": { "start": 3, "end": 5 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Tales from the Yawning Portal: The Hidden Shrine of Tamoachan",
        "id": "TftYP-THSoT",
        "source": "TftYP-THSoT",
        "coverUrl": "img/covers/TftYP.png",
        "published": "2017-03-24",
        "publishedOrder": 2,
        "storyline": "Tales from the Yawning Portal",
        "level": { "start": 5, "end": 8 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Tales from the Yawning Portal: The Sunless Citadel",
        "id": "TftYP-TSC",
        "source": "TftYP-TSC",
        "coverUrl": "img/covers/TftYP.png",
        "published": "2017-03-24",
        "publishedOrder": 0,
        "storyline": "Tales from the Yawning Portal",
        "level": { "start": 1, "end": 3 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Tales from the Yawning Portal: Tomb of Horrors",
        "id": "TftYP-ToH",
        "source": "TftYP-ToH",
        "coverUrl": "img/covers/TftYP.png",
        "published": "2017-03-24",
        "publishedOrder": 6,
        "storyline": "Tales from the Yawning Portal",
        "level": { "custom": "Higher level" },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Tales from the Yawning Portal: White Plume Mountain",
        "id": "TftYP-WPM",
        "source": "TftYP-WPM",
        "coverUrl": "img/covers/TftYP.png",
        "published": "2017-03-24",
        "publishedOrder": 3,
        "storyline": "Tales from the Yawning Portal",
        "level": { "start": 8, "end": 9 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Tomb of Annihilation",
        "id": "ToA",
        "source": "ToA",
        "coverUrl": "img/covers/ToA.png",
        "published": "2017-09-19",
        "storyline": "Tomb of Annihilation",
        "level": { "start": 1, "end": 11 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "The Tortle Package",
        "id": "TTP",
        "source": "TTP",
        "coverUrl": "img/covers/TTP.png",
        "published": "2017-11-03",
        "storyline": "Tomb of Annihilation",
        "level": { "start": 1, "end": 4 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Waterdeep: Dragon Heist",
        "id": "WDH",
        "source": "WDH",
        "coverUrl": "img/covers/WDH.png",
        "published": "2018-09-18",
        "storyline": "Waterdeep",
        "level": { "start": 1, "end": 5 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Lost Laboratory of Kwalish",
        "id": "LLK",
        "source": "LLK",
        "coverUrl": "img/covers/LLK.png",
        "published": "2018-11-10",
        "storyline": "Extra Life",
        "level": { "start": 5, "end": 10 },
        "spells": "true",
        "type": "adventure"
      },
      {
        "name": "Waterdeep: Dungeon of the Mad Mage",
        "id": "WDMM",
        "source": "WDMM",
        "coverUrl": "img/covers/WDMM.png",
        "published": "2018-11-13",
        "storyline": "Waterdeep",
        "level": { "start": 5, "end": 20 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Krenko's Way",
        "id": "KKW",
        "source": "KKW",
        "coverUrl": "img/covers/GGR.png",
        "published": "2018-11-20",
        "storyline": "Ravnica",
        "level": { "start": 1, "end": 2 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Ghosts of Saltmarsh",
        "id": "GoS",
        "source": "GoS",
        "coverUrl": "img/covers/GoS.png",
        "published": "2019-05-21",
        "storyline": "Ghosts of Saltmarsh",
        "level": { "start": 1, "end": 12 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Hunt for the Thessalhydra",
        "id": "HftT",
        "source": "HftT",
        "coverUrl": "img/covers/HftT.png",
        "published": "2019-05-21",
        "storyline": "Stranger Things",
        "level": { "start": 3, "end": 4 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "The Orrery of the Wanderer",
        "id": "OoW",
        "source": "OoW",
        "coverUrl": "img/covers/AI.png",
        "published": "2019-06-18",
        "storyline": "Acquisitions Incorporated",
        "level": { "start": 1, "end": 6 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Essentials Kit: Dragon of Icespire Peak",
        "id": "DIP",
        "source": "DIP",
        "coverUrl": "img/covers/ESK.png",
        "published": "2019-06-24",
        "publishedOrder": 0,
        "storyline": "Essentials Kit",
        "level": { "start": 1, "end": 6 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Essentials Kit: Divine Contention",
        "id": "DC",
        "source": "DC",
        "coverUrl": "img/covers/ESK.png",
        "published": "2019-09-03",
        "publishedOrder": 3,
        "storyline": "Essentials Kit",
        "level": { "start": 11, "end": 12 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Essentials Kit: Storm Lord's Wrath",
        "id": "SLW",
        "source": "SLW",
        "coverUrl": "img/covers/ESK.png",
        "published": "2019-09-03",
        "publishedOrder": 1,
        "storyline": "Essentials Kit",
        "level": { "start": 7, "end": 9 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Essentials Kit: Sleeping Dragon's Wake",
        "id": "SDW",
        "source": "SDW",
        "coverUrl": "img/covers/ESK.png",
        "published": "2019-09-03",
        "publishedOrder": 2,
        "storyline": "Essentials Kit",
        "level": { "start": 9, "end": 11 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Baldur's Gate: Descent Into Avernus",
        "id": "BGDIA",
        "source": "BGDIA",
        "coverUrl": "img/covers/BGDIA.png",
        "published": "2019-09-18",
        "storyline": "Baldur's Gate",
        "level": { "start": 1, "end": 13 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Locathah Rising",
        "id": "LR",
        "source": "LR",
        "coverUrl": "img/covers/LR.png",
        "published": "2019-09-19",
        "storyline": "Extra Life",
        "level": { "start": 9, "end": 9 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Infernal Machine Rebuild",
        "id": "IMR",
        "source": "IMR",
        "coverUrl": "img/covers/IMR.png",
        "published": "2019-11-12",
        "storyline": "Extra Life",
        "level": { "start": 5, "end": 10 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Eberron: Forgotten Relics",
        "id": "EFR",
        "source": "EFR",
        "coverUrl": "img/covers/ERLW.png",
        "published": "2019-11-19",
        "storyline": "Eberron",
        "level": { "start": 1, "end": 2 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "The Lost Dungeon of Rickedness: Big Rick Energy",
        "id": "RMBRE",
        "source": "RMBRE",
        "coverUrl": "img/covers/RMR.png",
        "published": "2019-11-19",
        "storyline": "Rick and Morty",
        "level": { "start": 1, "end": 3 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Wildemount: Frozen Sick",
        "id": "FS",
        "source": "FS",
        "coverUrl": "img/covers/EGW.png",
        "published": "2020-03-17",
        "publishedOrder": 2,
        "storyline": "Wildemount",
        "level": { "start": 1, "end": 3 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Wildemount: Dangerous Designs",
        "id": "DD",
        "source": "DD",
        "coverUrl": "img/covers/EGW.png",
        "published": "2020-03-17",
        "publishedOrder": 1,
        "storyline": "Wildemount",
        "level": { "start": 1, "end": 3 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Wildemount: Unwelcome Spirits",
        "id": "US",
        "source": "US",
        "coverUrl": "img/covers/EGW.png",
        "published": "2020-03-17",
        "publishedOrder": 3,
        "storyline": "Wildemount",
        "level": { "start": 1, "end": 3 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Wildemount: Tide of Retribution",
        "id": "ToR",
        "source": "ToR",
        "coverUrl": "img/covers/EGW.png",
        "published": "2020-03-17",
        "publishedOrder": 0,
        "storyline": "Wildemount",
        "level": { "start": 1, "end": 3 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "No Silent Secret",
        "id": "MOT-NSS",
        "source": "MOT",
        "coverUrl": "img/covers/MOT.png",
        "published": "2020-06-02",
        "storyline": "Mythic Odysseys of Theros",
        "level": { "start": 1, "end": 2 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Icewind Dale: Rime of the Frostmaiden",
        "id": "IDRotF",
        "source": "IDRotF",
        "coverUrl": "img/covers/IDRotF.png",
        "published": "2020-09-15",
        "storyline": "Icewind Dale",
        "level": { "start": 1, "end": 12 },
        "spells": "true",
        "type": "adventure"
      },
      {
        "name": "Candlekeep Mysteries",
        "id": "CM",
        "source": "CM",
        "coverUrl": "img/covers/CM.png",
        "published": "2021-03-16",
        "storyline": "Candlekeep Mysteries",
        "level": { "start": 1, "end": 16 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "The House of Lament",
        "id": "HoL",
        "source": "HoL",
        "coverUrl": "img/covers/VRGR.png",
        "published": "2021-05-18",
        "storyline": "Ravenloft",
        "level": { "start": 1, "end": 3 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Adventures in the Forgotten Realms: In Scarlet Flames",
        "id": "AitFR-ISF",
        "source": "AitFR-ISF",
        "coverUrl": "img/covers/AitFR-ISF.png",
        "published": "2021-06-30",
        "storyline": "Adventures in the Forgotten Realms",
        "level": { "start": 8, "end": 8 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Adventures in the Forgotten Realms: The Hidden Page",
        "id": "AitFR-THP",
        "source": "AitFR-THP",
        "coverUrl": "img/covers/AitFR-THP.png",
        "published": "2021-07-07",
        "storyline": "Adventures in the Forgotten Realms",
        "level": { "start": 8, "end": 9 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Adventures in the Forgotten Realms: A Verdant Tomb",
        "id": "AitFR-AVT",
        "source": "AitFR-AVT",
        "coverUrl": "img/covers/AitFR-AVT.png",
        "published": "2021-07-14",
        "storyline": "Adventures in the Forgotten Realms",
        "level": { "start": 9, "end": 9 },
        "spells": "true",
        "type": "adventure"
      },
      {
        "name": "Adventures in the Forgotten Realms: Darkest Night",
        "id": "AitFR-DN",
        "source": "AitFR-DN",
        "coverUrl": "img/covers/AitFR-DN.png",
        "published": "2021-07-21",
        "storyline": "Adventures in the Forgotten Realms",
        "level": { "start": 9, "end": 10 },
        "spells": "false",
        "type": "adventure"
      },
      {
        "name": "Adventures in the Forgotten Realms: From Cyan Depths",
        "id": "AitFR-FCD",
        "source": "AitFR-FCD",
        "coverUrl": "img/covers/AitFR-FCD.png",
        "published": "2021-07-28",
        "storyline": "Adventures in the Forgotten Realms",
        "level": { "start": 10, "end": 10 },
        "spells": "false",
        "type": "adventure"
      }
];